### ISSUE TITLE
Combine target and sorce language processor classes 

### ISSUE THREAD

**Issue by ascherdakova** [ascherdakova/MessagesProcessor#15]
SourceLanguageLoader.java and TargetLanguageLoader.java have to be united in order to avoid code duplication

**Comment by VasiliyMatutin** [comment]
@ascherdakova , I merged this two classes into one, but there is still some code duplication --> this is because of onClickListener lambda class. I can go further & create custom clickListener class, but I'm not sure it is reasonable (because it will create additional strange code). I reassign this task to you, so feel free to close it if you think that all done already.
